from MessageQueue import MakePaymentReminder, GenerateInvoiceReminder, CompanyPaymentExpired,SignUpValidationEmail, MemberInvitationEmail, ResetPasswordEmail, CompanyDocSubmiitedEmail, CompanyApproveEmail, CompanyRejectEmail, ReminderNotificationEmail, MemberRejectEmail, SendNotification, CheckInvoicePaid, CompanyDeferEmail, GenerateContractEmail, CheckMedicalSurvey, coveragePartiallyRejectedEmail, CoverageRenewalNotification, CheckMemberAcceptOffer, ChangePaymentModeEmail, ChangePaymentDueDateEmail
from apscheduler.schedulers.background import BackgroundScheduler

def start():
    scheduler = BackgroundScheduler()
    scheduler.add_job(SignUpValidationEmail.sendEmail, 'interval', seconds=5)
    scheduler.add_job(MemberInvitationEmail.sendEmail, 'interval', seconds=5)
    scheduler.add_job(ResetPasswordEmail.sendEmail, 'interval', seconds=5)
    scheduler.add_job(CompanyDocSubmiitedEmail.sendEmail, 'interval', seconds=5)
    scheduler.add_job(CompanyApproveEmail.sendEmail, 'interval', seconds=5)
    scheduler.add_job(CompanyRejectEmail.sendEmail, 'interval', seconds=5)
    scheduler.add_job(ReminderNotificationEmail.reminder, 'interval', seconds=5)
    scheduler.add_job(ReminderNotificationEmail.sendEmail, 'interval', seconds=5)
    scheduler.add_job(MemberRejectEmail.sendEmailMemberReject, 'interval', seconds=5)
    scheduler.add_job(SendNotification.sendNotification, 'interval', seconds=5)
    scheduler.add_job(CheckInvoicePaid.checkInvoicePaid, 'interval', seconds=5)
    scheduler.add_job(CompanyDeferEmail.sendEmail, 'interval', seconds=5)
    scheduler.add_job(GenerateContractEmail.sendEmail, 'interval', seconds=5)
    scheduler.add_job(SendNotification.sendNotificationSponsoredInsurance, 'interval', seconds=5)
    scheduler.add_job(MemberRejectEmail.sendEmailMedicalSurveyFailed, 'interval', seconds=5)
    scheduler.add_job(MemberRejectEmail.sendEmailMemberActiveSI, 'interval', seconds=5)
    scheduler.add_job(MakePaymentReminder.sendEmail, 'interval', seconds=5)
    scheduler.add_job(MakePaymentReminder.reminder, 'interval', seconds=5)
    scheduler.add_job(GenerateInvoiceReminder.sendEmail, 'interval', seconds=5)
    scheduler.add_job(GenerateInvoiceReminder.reminder, 'interval', seconds=5)
    scheduler.add_job(CompanyPaymentExpired.sendEmail, 'interval', seconds=5)
    scheduler.add_job(SendNotification.ekycNotification, 'interval', seconds=5)
    scheduler.add_job(coveragePartiallyRejectedEmail.sendEmail, 'interval', seconds=5)
    scheduler.add_job(CheckMedicalSurvey.checkMedicalSurvey, 'interval', seconds=5)
    scheduler.add_job(CoverageRenewalNotification.sendEmail, 'interval', seconds=5)
    scheduler.add_job(CoverageRenewalNotification.reminder, 'interval', seconds=30)
    scheduler.add_job(CheckMemberAcceptOffer.memberAcceptedStatus, 'interval', seconds=5)
    # Add a job to run renewal notification every day at 9 AM and 5 PM
    # scheduler.add_job(CoverageRenewalNotification.sendEmail, 'cron', hour='9,17')
    # scheduler.add_job(CoverageRenewalNotification.reminder, 'cron', hour='9,17')
    
    scheduler.add_job(ChangePaymentModeEmail.sendEmail, 'interval', seconds=5)
    scheduler.add_job(ChangePaymentDueDateEmail.sendEmail, 'interval', seconds=5)
    scheduler.start()