# Generated by Django 4.1.3 on 2023-09-07 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0002_corporateprofile_payment_mode_member_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyformtype',
            name='upload_type',
        ),
        migrations.AddField(
            model_name='companyformtype',
            name='form_type_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='corporateprofile',
            name='deferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='click_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_reminder',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='invoice_reminder_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='sendinvitation_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyformtype',
            name='description',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='companyformtype',
            name='form_type_name',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='member',
            name='mobile_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='mykad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_datetime', models.DateTimeField(auto_now=True)),
                ('updated_datetime', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Entity Type',
                'db_table': 'EntityType',
            },
        ),
        migrations.AddField(
            model_name='companyformtype',
            name='entity_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Portal.entitytype'),
        ),
        migrations.AddField(
            model_name='corporateprofileformattachment',
            name='entity_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Portal.entitytype'),
        ),
    ]
