# Generated by Django 4.1.3 on 2023-09-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0003_remove_companyformtype_upload_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='read_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='updated_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
