# Generated by Django 4.1.3 on 2023-10-30 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0006_currentdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_premium', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('generated_invoice', models.BooleanField(default=False)),
                ('void', models.BooleanField(default=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portal.member')),
            ],
            options={
                'verbose_name_plural': 'Premium Adjustment',
                'db_table': 'PremiumAdjustment',
            },
        ),
    ]
