# Generated by Django 4.1.3 on 2023-11-17 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0007_premiumadjustment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentModeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(blank=True, null=True)),
                ('old_payment_due_date', models.CharField(max_length=25)),
                ('old_payment_mode', models.CharField(max_length=25)),
                ('new_payment_due_date', models.CharField(max_length=25)),
                ('new_payment_mode', models.CharField(max_length=25)),
                ('is_updated', models.BooleanField(default=False)),
                ('is_void', models.BooleanField(default=False)),
                ('corporate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portal.corporateprofile')),
            ],
            options={
                'verbose_name_plural': 'PaymentModeHistory',
                'db_table': 'PaymentModeHistory',
            },
        ),
    ]
