# Generated by Django 4.1.3 on 2024-10-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0008_paymentmodehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporateprofile',
            name='corporate_campaign_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='campaign_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
